# Generated by Django 4.1.7 on 2023-03-24 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_work', models.DateField(default=datetime.date(2023, 3, 23), verbose_name='Day of work')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('break_length', models.DurationField(verbose_name='Time taken for break')),
            ],
        ),
    ]
