# Generated by Django 4.1.7 on 2023-03-24 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrack', '0002_times_delete_timetrackermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='date_of_work',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 22, 9, 13, 914686), verbose_name='Day of work'),
        ),
        migrations.AlterField(
            model_name='times',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='times',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
