# Generated by Django 4.1.7 on 2023-03-25 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrack', '0003_alter_times_date_of_work_alter_times_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='break_length',
            field=models.DurationField(blank=True, verbose_name='Time taken for break'),
        ),
        migrations.AlterField(
            model_name='times',
            name='date_of_work',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 25, 8, 24, 30, 62604), verbose_name='Day of work'),
        ),
        migrations.AlterField(
            model_name='times',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 25, 8, 24, 30, 62639), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='times',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 25, 8, 24, 30, 62630), verbose_name='Start Time'),
        ),
    ]
