# Generated by Django 4.1.7 on 2023-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrack', '0004_alter_times_break_length_alter_times_date_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='date_of_work',
            field=models.DateTimeField(blank=True, verbose_name='Day of work'),
        ),
        migrations.AlterField(
            model_name='times',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='times',
            name='start_time',
            field=models.DateTimeField(blank=True, verbose_name='Start Time'),
        ),
    ]
