# Generated by Django 4.1.7 on 2023-03-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrack', '0006_alter_times_break_length_alter_times_date_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='date_of_work',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 25, 8, 28, 49, 788310), verbose_name='Day of work'),
        ),
    ]
