# Generated by Django 4.1.7 on 2023-03-25 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrack', '0008_alter_times_date_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='date_of_work',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 25, 8, 30, 39, 263033, tzinfo=datetime.timezone.utc), verbose_name='Day of work'),
        ),
    ]
