# Generated by Django 4.1.7 on 2023-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrack', '0011_alter_times_date_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='times',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
